### ISSUE TITLE
BSC - Analisis Journals

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/BSC#25]
Se deben analizar los procesos enviados por Carrizo para implementar en BSC

**Comment by jmusanti** [comment]
1.	Ver el volumen de txs que le interesa a Nico tener en BI
2.	Proponer a Nico para generar el id cuenta utilizar la que tiene max(fecha_alta)
3.	Proponer a Pablo:
a.	Armar un ETL que ejecute los SP que corre hoy
b.	Llevar los id_cuenta de CA y CC para poder resolver el punto 1 a Journals (se necesita el Producto) (si no joinea poner valor default)
4.	En la base de pruebas, a la tabla de txs journals agregar un campo id_cuenta, ver si podemos usar índices. Armar paquete.

**Comment by tserra98** [comment]
Se envio script para obtener resultados en produccion y ver si las txs faltantes son por problema de replica de base o problema del banco.

**Comment by tserra98** [comment]
Se notifico a nico que las txs faltantes no aparecen ni en produccion

**Comment by tserra98** [comment]
Pablo: buenas tardes, estamos teniendo diferencias entre los días que se ven cargadas en BI test contra los días que yo veo en producción (servidor VM001F2K00.)

Según me dijo Joaquín ellos están utilizando la tabla Sucursales_Journals para cargar los datos, como ejemplo tomo la sucursal de Rio Gallegos y veo que para los días 21/03, 30/05 y 31/05 no se registran transacciones. Pero si  realizo la misma consulta en la tabla MainTxnJournal de servidor VM001F2K00 perteneciente a la sucursal de Rio Gallegos para los días mencionado trae transacciones realizadas.

Podrás por favor revisarlo.

Avísame cualquier cosa.

Saludos.

**Comment by tserra98** [comment]
esperando permisos sobre la base

**Comment by tserra98** [comment]
Se dejo el pase a prod de esta tarea a Belen.
