### ISSUE TITLE
BSC - Muestreo de clientes Sector Privado No Financiero

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/BSC#67]
Joaquín / Pablo: se podrá armar un muestreo de clientes que hayan retirado por caja cheques mayores a $50.000? Sector Privado no financiero

Este informe se realiza mensualmente.

Aguardo comentarios!

Saludos!

**Comment by jmusanti** [comment]
Cecilia nos pide que los cheques no esten sumarizados. Se debe hacer la consulta del Cuentas_Transacciones

**Comment by PabloGottig** [comment]
Se solicitó a Belén que implementen un cambio en la vista para contar con un Random a nivel tabla.

**Comment by tserra98** [comment]
Esperando pase a produccion de belen para agregar el usuario al rpt de andrea.

**Comment by tserra98** [comment]
Se agrego el campo usuario, y se le notifico a Andrea para que lo valide y nos diga si falta otro campo.

**Comment by tserra98** [comment]
enviar nuevo correo a andrea para recordar que valide esto

**Comment by tserra98** [comment]
Buen día Tomas, no aun no pude, tengo que ver cómo sacar el reporte de BI de las transacciones causales para saber si está tomando todas.
