### ISSUE TITLE
BSC - Reporte Clientes para GAC

### ISSUE THREAD

**Issue by tserra98** [brosenburt/BSC#70]
Hola a todos.

Lo que necesitamos es lo siguiente: un reporte de generación mensual, que tome para todos los cliente cuyo IGR promedio sea medio o bajo, el total de créditos recibidos por mes (en esos esta el acumulador 44) para los últimos 6 meses.
Una vez obtenidos los créditos de los 6 meses, se acomoden todas las operaciones de menor a mayor, se elimine el datos de la operación más baja (distinta de cero) y se elimine la operación de mayor importe  (en ambos casos para los últimos 6 meses) y ese acumulado de créditos (menos los extremos) se divida por 6, ese valor será el resultado a informar por cliente, que debemos poder exportar en Excel.

Para los clientes que tengan menos de 6 meses de créditos, se tomaran los meses disponibles, esto es para los clientes que tiene menos de 6 meses de antigüedad en la entidad (no aplica a clientes que tiene más de 6 meses de antigüedad y algunos meses pueden tener 0 acreditaciones, estos meses igual se contemplan).

Los datos de antigüedad, hay que tomarlo de la fecha de lata del cliente en sfb
El dato de créditos desde los acumuladores de sos o directo desde las tran causales parametrizadas para sos como créditos consolidados
El máximo y el mínimo de las operaciones de cada mes es un dato que esta en sos también, pero no sé como lo van a armar.

Avisanos y vamos avanzando.

**Comment by jmusanti** [comment]
1) Extraer los clientes de la fact_indicadores_cliente con IGRPROMEDIO medio o bajo y cruzarlos con la tabla ACUMULADOR_044 de SOS. Traer de la IGRPROMEDIO los 6 ultimos meses. Calcular tambien la antiguedad en meses del cliente. Restar al acumulado el minimo y el maximo
2) Cargar en una tabla para cada cliente el acumulado dividido la cantidad de meses correspondiente
3) Cargar al universo de PLA la nueva tabla y modelarla
4) Crear un reporte para mostrar lo que se encuentra en dicha tabla para un mes en particular

**Comment by tserra98** [comment]
Solucionar error que tira esta tarea y avanzar con la planning de esto.

declare 
fecha_desde date:=trunc(?);
fecha_hasta date:=trunc(?);

begin
insert into dods.tmp_fact_creditos_consolidados(
  fecha,
  cuit,
  acum,
  maximo,
  minimo,
  antiguedad,
  igrpromedio)
select 
  fecha_hasta,
  t.cuit,
  sum(t.acum),
  max(t.maximo),
  min(t.minimo),
  abs(fecha_hasta - dp.fecha_alta),
  ic.indiceriesgoprom  
from dods.tmp_acumuladores_44 t left join ddw.dim_personas dp on t.cuit = dp.clave_unica_identificacion_tri
     left join ddw.fact_indicadores_cliente ic on ic.persona_key = dp.persona_key 
where (to_date(concat(concat(t.anio, t.mes), '01'), 'yyyyMMdd') between fecha_desde and fecha_hasta)
      and ic.indiceriesgoprom <= 67.9999 /*maximo valor para que el valor sea medio*/
group by t.cuit,
  ic.indiceriesgoprom  ;

commit;
end;

**Comment by tserra98** [comment]
Queda por analizar cruces en el universo. Y crear reporte para validacion de datos

**Comment by tserra98** [comment]
Queda crear tarea que carga dw_procesos, poniendo que cargue 6 meses.

**Comment by tserra98** [comment]
Lunes enviar recordatorio a natalia sobre este tema.

**Comment by tserra98** [comment]
respuesta de natalia: Tomas, buen día
NO aun, esta semana les enviamos respuesta.

**Comment by tserra98** [comment]
Verificado, cumple con lo solicitado…

Lo único que se observa es que en algunos casos el NIT no corresponde con el CUIT del cliente:

Ejemplo: Cambios Del Sur SA, corresponde a cliente 193590 y en el reporte me trajo lo siguiente:

 	30/11/2018	33716000449	193283	1704035	2	852017.5	40.4

Fuera de ese dato todo el resto está relacionado con el CUIT.

Encontré varios casos de números de clientes que no existen.

**Comment by tserra98** [comment]
se le pregunto a carlos el criterio a tomar para la carga de nit en la tabla tmp_acum_44.

**Comment by tserra98** [comment]
se reproceso , se modifico filtro de fecha en el rpt y se envio a validacion

**Comment by tserra98** [comment]
Tomi, el índice lo estás tomando de la fact de indicadores? No puede ser que es fact esté mal cargada para ese período? Pueden verificar el dato en SOS?

**Comment by tserra98** [comment]
ver modificacion que menciono pablo, no traer los datos de sos

**Comment by tserra98** [comment]
se modifico carga de la int_creditos_consolidados, ahora trae nit ejemplo que menciono carlos. Resta ver si avisamos que se modifico y que validen

**Comment by tserra98** [comment]
analizar coherencia del nuevo cambio y mandar a validar

**Comment by tserra98** [comment]
Se dejo pase a produccion del reporte a belen
