### ISSUE TITLE
BSC - Modificacion de reporte Entes Publicos

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/BSC#79]
Joaquin/Pablo,
        Buenas tardes, les consulto respecto del reporte ENT - Pago de Cheques, el cual es un ranking de Principales 10 cheques pagados a titulares de Sector Público sin distinción de Riesgo.
 
1.	Se puede ampliar en el ranking la cantidad de 10 a 20 cheques?
2.	Se puede agregar para cada cheque: sucursal, cuenta y digito verificador?
3.	Y N° de Cliente del Ente.
 
 
Atte.-

**Comment by tserra98** [comment]
Esperando confirmacion de carlos.

**Comment by tserra98** [comment]
Se le envio correo a Carlos preguntando si vio el reporte.

**Comment by tserra98** [comment]
enviar nuevo correo a carlos para recordar que revise esto
