### ISSUE TITLE
BER - Modificacion de formato de archivos MC

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/BSC#84]
Pablo, buenas tardes.

Te molesto por que fueron modificados los diseños de los archivos de mastercard que utilizamos en el proceso Mensual de Tarjetas de Crédito. 

Me entere hoy a raíz de averiguar el motivo de la cancelación del proceso:

 

Por lo que veo se modificaron los diseños de movimientos y cuentas. Únicamente se modificaron los campos de “Importe”. Pasaron de long. 7 a long. 11 

Adjunto el diseño Nuevo y el anterior.

Esto lo vamos a necesitar para procesar la última base enviada por MC.

Por favor confirmanos que tiempos disponen para modificar los procesos y si necesitas que te pasemos el paquete.

Saludos.-
Maximiliano M. Ottino
Tecnología y Sistemas | Sistemas Departamentales
Tel 0343-4201359

**Comment by PabloGottig** [comment]
Se incorporaron los campos nuevos a las facts. FALTA MODIFICAR EL UNIVERSO.
