### ISSUE TITLE
BSF - Modelo Comunicaciones

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/BSC#87]

**Comment by PabloGottig** [comment]
Probar los archivos de Abril, May y Jun 19 con la nueva planilla de Linea / Persona

**Comment by PabloGottig** [comment]
Es importante depurar la base de lineas personas y rrhh porque quedan muchisimos casos sin asignar.

**Comment by PabloGottig** [comment]
![image.png](https://images.zenhubusercontent.com/5beef8c5308256459932e5c1/a7b7527a-26b2-4dbd-9c2d-2c173daf53b9)


Analizar estos casos
